# Versión del formato de Docker Compose
version: '3.8'

services:
  app:
    build: .
    container_name: videogames-app-php
    ports:
      - "8000:80"
    # Monta el código de tu carpeta 'src' en el contenedor
    # Esto permite que los cambios en tu código se reflejen sin reconstruir la imagen
    volumes:
      - ./src:/var/www/html/
      - vendor_data:/var/www/html/vendor
    env_file:
      - .env
    networks:
      - app-network

  # Servicio para tu base de datos MySQL
  db:
    image: mysql:8.0
    container_name: videogames-db-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    volumes:
      - db-data:/var/lib/mysql
      # --- LÍNEA A AÑADIR ---
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

# Definición de las redes
networks:
  app-network:
    driver: bridge

# Definición de los volúmenes para persistencia de datos
volumes:
  db-data:
  vendor_data: